=== jaehyeonKyeong/backup/jsp_prj/WebContent/xml0820/dept_attr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT depts (dept*)>
<!ELEMENT dept (deptno?,dname+,loc+)>
<!ELEMENT deptno (#PCDATA)>
<!ELEMENT dname (#PCDATA)>
<!ELEMENT loc (#PCDATA)>

<!-- IMPLIED - 속성의 값은 없으며 생략가능한 속성 -->
<!ATTLIST dname dept_info CDATA #IMPLIED >
<!-- DEFAULT - 속성을 정의하지 않으면 #DEFAULT이고 노드정의시 속성을 생략하면 설정된 값이 기본값으로 들어간다 -->
<!ATTLIST loc location CDATA "서울">
<!-- FIXED - 속성을 사용하면 정해진 값만 설정할 때 노드 정의시 속성을 생략할 수 있고, 속성이 정의 된다면 정해진 값(SIST)만 사용할 수 있다. -->
<!ATTLIST deptno company CDATA #FIXED "SIST">
<!-- 
REQUIRED - 속성을 반드시 정의해야 할 때 (속성의 값은 없음)
-->
<!ATTLIST dname dept_nick CDATA #REQUIRED>

=== jaehyeonKyeong/backup/jsp_prj/WebContent/xml0820/dtd_dept.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE depts SYSTEM "dept_attr.dtd">
<depts>
	<dept>
		<deptno company="SIST">10</deptno>
		<dname dept_nick="생산하는 일" dept_info="스킬업">SI</dname>
		<loc location="서울">서울</loc>
	</dept>
	<!-- fixed : company는 SIST만 가능하다 -->
	<dept>
		<deptno company="SIST">20</deptno>
		<!--ERROR <deptno company="JUONET">20</deptno> -->
		<dname dept_nick="upsert 하는 일" dept_info="정시퇴근 가능">SM</dname>
		<loc location="서울">서울</loc>
	</dept>
	<!-- required : dept_nick속성은 반드시 정의해야한다. 
		Default: location은 기본값이 들어가나 다른 값으로 변경할수 있다
		implied : 생략가능하고 자유롭게 값을 넣을 수 있다.
		-->
	<dept>
		<deptno company="SIST">30</deptno>
		<dname dept_nick="upsert 하는 일" dept_info="정시퇴근 가능">Solution</dname>
		<!-- ERROR <dname dept_info="정시퇴근 가능">Solution</dname> -->
		<loc location="파프리카">파주</loc>
	</dept>
</depts>
